//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realms
    {
        public string RealmID { get; set; }
        public string RealmDes { get; set; }
        public string OpenID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ParentID { get; set; }
        public long Sequence { get; set; }
        public string Uri { get; set; }
    }
}
