//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteonWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrueLiteonDBEntities2 : DbContext
    {
        public TrueLiteonDBEntities2()
            : base("name=TrueLiteonDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dic_Regions> Dic_Regions { get; set; }
        public virtual DbSet<Logging> Logging { get; set; }
        public virtual DbSet<Realms> Realms { get; set; }
        public virtual DbSet<RoleRealms> RoleRealms { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ThirdPartyIDs> ThirdPartyIDs { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserOutMappings> UserOutMappings { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
