//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteonWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string GUID { get; set; }
        public string UserName { get; set; }
        public string EmployeeID { get; set; }
        public string Region { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string UserID { get; set; }
    }
}
